AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAIL-generated SAM template for Spring Boot application

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: java17

Resources:
  SailFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
      Environment:
        Variables:
          SPRING_PROFILES_ACTIVE: aws
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
        RootPath:
          Type: Api
          Properties:
            Path: /
            Method: ANY

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/'
  FunctionName:
    Description: Lambda Function name
    Value: !Ref SailFunction

